version: "3.8"

services:
  redis:
    image: redis
    restart: always
    
  
  database:
    image: postgres:13.3
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  webapp:
    restart: always
    depends_on:
      - database
    env_file:
      - ./.env
    build:
      context: .
    stdin_open: true
    tty: true
    ports:
      - 8000:8000
    # command: sh -c "python3 manage.py flush --noinput"
    command: sh -c "python3 manage.py makemigrations &&
                    python3 manage.py migrate &
                    python3 manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./media/img/:/media/img/
    depends_on:
      - worker
    
  worker:
    restart: always
    build:
      context: .
    command: ["celery", "--workdir=./", "-A", "krassite", "worker"]
    env_file:
      - ./.env
          
volumes:
  postgres_data:
